POST http://localhost:3001/api/auth/login HTTP/1.1
Content-type: application/json

{
    "email": "user1@user1.com",
    "password": "user1"
}

###

POST http://localhost:3001/api/auth/signup HTTP/1.1
Content-type: application/json

{
    "email": "user2@user2.com",
    "username": "User 2",
    "password": "user2"
}